# Generated by Django 4.2.8 on 2023-12-08 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
